### ISSUE TITLE
请求帮助，使用task_create无法建任务

### ISSUE THREAD

**Issue by GbingSong** [philip1134/pyzentao#3]
tasks.data 返回了这些

{'title': 'xxxx-建任务', 'customFields': {'story': '相关需求', 'estStarted': '预计开始', 'deadline': '截止日期', 'mailto': '抄送给', 'pri': '优先级', 'estimate': '最初预计'}.....

官方文档上的这些参数改如何填写呢？

    $params = array(
        'project'          => 1,
        'type'             => 'ui',
        'module'           => 0,
        'assignedTo[]'     => 'lisi',
        'testAssignedTo[]' => 'lisi',
        'color'            => '',
        'name'             => '测试添加任务2',
        'pri'              => 2,
        'estimate'         => 1,
        'desc'             => '测试添加任务描述测试添加任务描述',
        'estStarted'       => '2019-11-11',
        'deadline'         => '2019-11-12',
        'mailto[1]'        => 'lisi'
    );    // 请求参数

**Comment by philip1134** [comment]
更新到0.3.0版本，post参数可使用data传入，例如

```
response = zentao.task_create(
    executionID=2,
    storyID=0,
    moduleID=0,
    ...
    data={
        "execution": 2,
        "type": "design",
        "name": "锦囊喵叽",
        "assignedTo[]": "老六",
        "pri": 3,
        "desc": "暴打小柯基"
        ...
    },
)
```

**Comment by GbingSong** [comment]
成啦,感谢!
